[package]
name = "libcanon"
version = "0.1.0"
edition = "2021"

[lib]
name = "libcanon"
path = "src/lib.rs"

[dependencies]
dirs = "5.0.1"
git2 = "0.19.0"
grep-regex = "0.1.13"
grep-searcher = "0.1.14"
ignore = "0.4.23"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
